Repository cloudforet-io/dashboard, pull requests merged in 2023-12, with the labels that each got.

#33 refactor: change all apis for SpaceONE 2.0
  Dockerfile
  deploy/helm/Chart.yaml
  deploy/helm/config/config.yaml
  deploy/helm/templates/deployment-rest.yaml
  deploy/helm/templates/deployment-scheduler.yaml
  deploy/helm/templates/deployment-worker.yaml
  src/setup.py
  src/spaceone/__init__.py
  src/spaceone/dashboard/conf/global_conf.py
  src/spaceone/dashboard/conf/proto_conf.py
  src/spaceone/dashboard/error/__init__.py
  src/spaceone/dashboard/error/dashboard.py
  src/spaceone/dashboard/info/__init__.py
  src/spaceone/dashboard/info/common_info.py
  src/spaceone/dashboard/info/custom_widget_info.py
  src/spaceone/dashboard/info/dashboard_info.py
  src/spaceone/dashboard/info/dashboard_version_info.py
  src/spaceone/dashboard/info/domain_dashboard_info.py
  src/spaceone/dashboard/info/domain_dashboard_version_info.py
  src/spaceone/dashboard/info/project_dashboard_info.py
  src/spaceone/dashboard/info/project_dashboard_version_info.py
  src/spaceone/dashboard/interface/grpc/__init__.py
  src/spaceone/dashboard/interface/grpc/dashboard.py
  src/spaceone/dashboard/interface/grpc/v1/__init__.py
  src/spaceone/dashboard/interface/grpc/v1/custom_widget.py
  src/spaceone/dashboard/interface/grpc/v1/domain_dashboard.py
  src/spaceone/dashboard/interface/grpc/v1/project_dashboard.py
  src/spaceone/dashboard/manager/__init__.py
  src/spaceone/dashboard/manager/custom_widget_manager.py
  src/spaceone/dashboard/manager/dashboard_manager.py
  src/spaceone/dashboard/manager/dashboard_version_manager.py
  src/spaceone/dashboard/manager/domain_dashboard_manager.py
  src/spaceone/dashboard/manager/domain_dashboard_version_manager.py
  src/spaceone/dashboard/manager/identity_manager.py
  src/spaceone/dashboard/manager/project_dashboard_manager.py
  src/spaceone/dashboard/manager/project_dashboard_version_manager.py
  src/spaceone/dashboard/model/__init__.py
  src/spaceone/dashboard/model/custom_widget_model.py
  src/spaceone/dashboard/model/dashboard_model.py
  src/spaceone/dashboard/model/dashboard_version_model.py
  src/spaceone/dashboard/model/domain_dashboard_model.py
  src/spaceone/dashboard/model/domain_dashboard_version_model.py
  src/spaceone/dashboard/model/project_dashboard_model.py
  src/spaceone/dashboard/model/project_dashboard_version_model.py
  src/spaceone/dashboard/service/__init__.py
  src/spaceone/dashboard/service/custom_widget_service.py
  src/spaceone/dashboard/service/dashboard_service.py
  src/spaceone/dashboard/service/domain_dashboard_service.py
  src/spaceone/dashboard/service/project_dashboard_service.py
  test/factory/__init__.py
  test/factory/custom_widget_dashboard_factory.py
  test/factory/domain_dashboard_factory.py
  test/factory/domain_dashboard_version_factory.py
  test/factory/project_dashboard_factory.py
  test/factory/project_dashboard_version_factory.py
  test/service/test_custom_widget.py
  test/service/test_domain_dashboard.py
  test/service/test_project_dashboard.py
Labels: enhancement

#34 fix: add class variable in Dashboard service
  src/spaceone/dashboard/service/dashboard_service.py
Labels: enhancement

#35 refactor: change Dashboard resource to PublicDashboard and PrivateDashboard
  src/spaceone/dashboard/info/__init__.py
  src/spaceone/dashboard/info/private_dashboard_info.py
  src/spaceone/dashboard/info/private_dashboard_version_info.py
  src/spaceone/dashboard/info/public_dashboard_info.py
  src/spaceone/dashboard/info/public_dashboard_version_info.py
  src/spaceone/dashboard/interface/grpc/__init__.py
  src/spaceone/dashboard/interface/grpc/private_dashboard.py
  src/spaceone/dashboard/interface/grpc/public_dashboard.py
  src/spaceone/dashboard/manager/__init__.py
  src/spaceone/dashboard/manager/dashboard_manager.py
  src/spaceone/dashboard/manager/dashboard_version_manager.py
  src/spaceone/dashboard/manager/private_dashboard_manager.py
  src/spaceone/dashboard/manager/private_dashboard_version_manager.py
  src/spaceone/dashboard/manager/public_dashboard_manager.py
  src/spaceone/dashboard/manager/public_dashboard_version_manager.py
  src/spaceone/dashboard/model/__init__.py
  src/spaceone/dashboard/model/private_dashboard_model.py
  src/spaceone/dashboard/model/private_dashboard_version_model.py
  src/spaceone/dashboard/model/public_dashboard_model.py
  src/spaceone/dashboard/model/public_dashboard_version_model.py
  src/spaceone/dashboard/service/__init__.py
  src/spaceone/dashboard/service/private_dashboard_service.py
  src/spaceone/dashboard/service/public_dashboard_service.py
Labels: enhancement

#37 fix: change PrivateDashboard permissions
  src/spaceone/dashboard/manager/private_dashboard_manager.py
  src/spaceone/dashboard/manager/private_dashboard_version_manager.py
  src/spaceone/dashboard/service/private_dashboard_service.py
  src/spaceone/dashboard/service/public_dashboard_service.py
Labels: bug, enhancement

#38 fix: add workspace_id in PrivateDashboard model
  src/spaceone/dashboard/info/private_dashboard_info.py
  src/spaceone/dashboard/model/private_dashboard_model.py
Labels: bug

#39 fix: remove user_id in PrivateDashboard service
  src/spaceone/dashboard/service/private_dashboard_service.py
Labels: bug

#40 fix: apply deduplicated logic when creating and updating PrivateDashboard resource
  src/spaceone/dashboard/model/private_dashboard_model.py
Labels: bug

#42 Fix public dashboard result error when workspace member search
  src/spaceone/dashboard/model/public_dashboard_model.py
Labels: bug
