Repository cloudforet-io/dashboard, pull requests merged in 2024-12, with the labels that each got.

#112 Add pivot operator when transforming data tables
  src/spaceone/dashboard/manager/data_table_manager/data_transformation_manager.py
Labels: enhancement

#113 Change the logic for obtaining data_keys and label_keys
  src/spaceone/dashboard/manager/data_table_manager/data_transformation_manager.py
Labels: pass/signedoff

#114 Additional Operator Development and Refactoring
  src/spaceone/dashboard/manager/data_table_manager/data_transformation_manager.py
Labels: enhancement, pass/signedoff

#140 refactor: change the sharing policy of public dashboard
  src/spaceone/dashboard/service/public_dashboard_service.py
  src/spaceone/dashboard/service/public_folder_service.py
Labels: pass/signedoff
